version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: web3signer
    ports:
      - "25434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d

  web3signer:
    image: consensys/web3signer:develop
    restart: always
    command:
      - --http-host-allowlist=*
      - eth2
      - --keystores-path=/validator_keys
      - --keystores-password-file=/validator_keys/passwords.txt
      - --slashing-protection-db-url=jdbc:postgresql://db:5432/web3signer
      - --slashing-protection-db-username=postgres
      - --slashing-protection-db-password=password
    ports:
      - "49200:9000"
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./validator_keys:/validator_keys

  nginx:
    image: nginx:latest
    ports:
      - "49201:443"
    volumes:
      - ./nginx/mycertificate.pem:/etc/nginx/ssl/mycertificate.pem
      - ./nginx/mykey.key:/etc/nginx/ssl/mykey.key
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      web3signer:
        condition: service_started
